### ISSUE TITLE
Verify all route handler paths are resulting in an response

### ISSUE THREAD

**Issue by philprime** [kula-app/OnLaunch#758]
# Details

I recently encountered connection issues with our PostgreSQL database.
I tried to test the write-capabilities by changing the name of an 'app', but the `HTTP PUT` never sent a response, because the error was caught instead of sent to the client.

# Tasks

- [x] Perform a detailed code review that all route handlers are sending a response, i.e. only `PrismaClientKnownRequestError` are caught here, while every other error should return an `HTTP 500` error.

https://github.com/kula-app/OnLaunch/blob/f093956828b8f5bd677b2b8d66fb837c4e40b9a9/pages/api/frontend/v0.1/orgs/%5BorgId%5D/apps/%5BappId%5D/index.ts#L95-L102

- [x] Add comments for return paths where the response is already handled, i.e. the function `getUserWithRoleFromRequest` sends responses in some cases, so add a comment in the `if (!user) { ... }` block

https://github.com/kula-app/OnLaunch/blob/f093956828b8f5bd677b2b8d66fb837c4e40b9a9/pages/api/frontend/v0.1/orgs/%5BorgId%5D/apps/%5BappId%5D/index.ts#L14-L18

- [x] Add a default response at the end of every route handler, i.e. something like this:

```ts
return res
  .status(StatusCodes.NOT_IMPLEMENTED)
  .json({ message: "Not implemented: unhandled response path" });
```
